First commit
AetherSeal/training pull request #1
Opened 2021-04-28 03:10 UTC by Delrahi24

2021-04-28 03:31 UTC, txileno requested changes
hay algunos comentarios que son de recomendación, otros si creo es mejor corregirlos

2021-04-28 03:31 UTC, txileno commented on index.html
> +          <br>
no usar para "salto de linea" o espacio entre un elemento y otro, usar
margin-top margin-bottom en el css del p y del image para asi obtener el mismo resultado, 

recomendación, ponerle una class al p e img, para no afectar el resto de los parrafos imagenes

2021-04-28 03:31 UTC, txileno commented on index.html
>      <title>Document</title>
agregar titulo de la página, 
quizás nombre de la tarea, nombre del autor que estás trabajando para una posible sección/categoria, etc

2021-04-28 03:31 UTC, txileno commented on styles.css
> +p {
corregir respecto al comentario que dejé en html, puedes modificar ambos o solo un elemento, segun veas conveniente tú

2021-04-28 03:31 UTC, txileno commented on styles.css
> +.image2 {
corregir respecto al comentario que dejé en html, puedes modificar ambos o solo un elemento, segun veas conveniente tú

2021-04-28 03:31 UTC, txileno commented on styles.css
> +    height: 500px;
agregar uso de max-width/height min-width/height es recomendado

2021-04-28 03:31 UTC, txileno commented on styles.css
> +    width: 250px;
agregar uso de max-width/height min-width/height es recomendado

2021-04-28 03:31 UTC, txileno commented on styles.css
> +body {
la tarea te pied el uso de un background color acorde a tu trabajo, si bien sé que blanco rinde, ponle otro color perezoso xD

2021-04-28 03:33 UTC, AetherSeal requested changes
cambialo y comitea de vuelta

2021-04-28 03:33 UTC, AetherSeal commented on styles.css
> +    font-size: 300%;
no uses % para los tamanos de las fuentes cambialo por unidades

2021-04-28 03:33 UTC, AetherSeal commented on styles.css
> +    margin-left: 5%;
warning: unidades no %  en esta ocasion dejalo asi

2021-04-28 03:33 UTC, macirex commented on index.html
> +        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
El texto no esta justificado

2021-04-28 03:33 UTC, macirex commented on styles.css
> +    width: 45%;
No usar porcentajes

2021-04-28 03:33 UTC, macirex commented on styles.css
> +    margin-right: 5%;
No usar porcentajes

2021-04-28 03:33 UTC, macirex commented on styles.css
> +    margin-right: 60%;
No usar porcentajes

2021-04-28 03:33 UTC, macirex commented on index.html
> +        <img src="dali.jpg" alt="dali-pic" class="image1">
las imagenes podrian en su directorio aparte

2021-04-28 03:33 UTC, macirex commented on styles.css
> +h1 {
Cuidado con definir propiedades para elementos html, ya que se aplican para todo el documento

2021-04-28 03:33 UTC, macirex commented on index.html
> +        <br>
Baneado el BR

2021-04-28 03:33 UTC, macirex commented on styles.css
> +.content {
Podrias haber puesto el  background-color: white; en esta clase en vez de sobrecargar el body

2021-04-28 03:33 UTC, macirex commented on styles.css
> +.image1 {
El posicionamiento de dali no esta correcto con respecto a la imagen original

2021-04-28 03:33 UTC, macirex commented on styles.css
> +.image2 {
El tamaño/dimension de la imagen no es el correcto o no se parece a la imagen original

2021-04-29 00:17 UTC, txileno requested changes
acomodar la identación en el html linea 26 del img

2021-04-29 00:17 UTC, txileno commented on index.html
> +          <img src="images/oleo.jpg" alt="oleo" class="image2">
acomodar identación de img, tiene 1 espacio de más

2021-04-29 00:40 UTC, txileno approved these changes

2021-05-04 01:20 UTC, AetherSeal approved these changes

2021-05-04 01:20 UTC, merged